cadena = input("Ingrese texto: ")
cadena = cadena.lower()
a = cadena.count("a")
e = cadena.count("e")
i = cadena.count("i")
o = cadena.count("o")
u = cadena.count("u")
print(f"La letra a se repite: {a} veces")
print(f"La letra e se repite: {e} veces")
print(f"La letra i se repite: {i} veces")
print(f"La letra o se repite: {o} veces")
print(f"La letra u se repite: {u} veces")
